const mongoose = require('mongoose')
mongoose.Promise = require('bluebird')
const Dish = require('../models/Dish')
const User = require('../models/User')
const dishData = require('./data/dishData')
const userData = require('./data/userData')
const { dbURI } = require('../config/environment')

mongoose.connect(dbURI, { useNewUrlParser: true })
  .then(() => mongoose.connection.db.dropDatabase())
  .then(() => Dish.create(dishData))
  .then(() => User.create(userData))
  .then(() => console.log('The seeds are here!'))
  .catch((err) => console.log(err))
  .finally(() => mongoose.connection.close())
